language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "4"
  - "6"
  - "8"
before_install:
  - if [[ `npm -v` != 5* ]]; then npm install -g npm@5; fi
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
script:
  - npm test
